### ISSUE TITLE
nearestStormDistance/nearestStormBearing return 0

### ISSUE THREAD

**Issue by bleedz** [f0xy/forecast.io-csharp#19]
When I display response data from any Lat/Lon, response.currently.nearestStormDistance and nearestStormBearing return 0.

I'm not sure if I'm missing anything or what might be happening during the parse, as I can't determine how to display the raw data returned from the server.

This is quick and dirty for display purposes only.

![2014-10-02_153228](https://cloud.githubusercontent.com/assets/9001477/4497880/81d2be3a-4a73-11e4-8e9c-b445a9297151.jpg)
![2014-10-02_153254](https://cloud.githubusercontent.com/assets/9001477/4497881/81e577d2-4a73-11e4-899d-88318643871e.jpg)

**Comment by f0xy** [comment]
This is definitely on the API side; please get in touch with Forecast.IO if you're still experiencing issues. @bleedz :+1:
