### ISSUE TITLE
Update version on NuGet with new endpoint URL

### ISSUE THREAD

**Issue by masta** [f0xy/forecast.io-csharp#40]
[The version on nuget.org](https://www.nuget.org/packages/Forecast.io) is still version 1.0.10 from August 23 2016.
The [change to the new DarkSky endpoint URL](https://github.com/f0xy/forecast.io-csharp/commit/0066799d6b073f910930fc7d3b311ae4b164b380) was made on September 20 2016.

Could you please create a new release for nuget.org?

Thank you very much

**Comment by masta** [comment]
It's been 12 days: Any update on this?

**Comment by nezmen** [comment]
Do we have some sort of ETA for this?

**Comment by f0xy** [comment]
Completed and published as 1.1.0

**Comment by masta** [comment]
Thank you so much! :-)
